// <auto-generated />
using CrudUsuario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudUsuario.Migrations
{
    [DbContext(typeof(ServiceContext))]
    partial class ServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CrudUsuario.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Diabetico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Edad")
                        .HasColumnType("numeric(2,0)");

                    b.Property<string>("Enfermedades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Identificacion")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Lentes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maneja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("NumeroTelefono")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("Id")
                        .HasName("PK_USUARIOS_4544DWF");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
